# Generated by Django 5.2.4 on 2025-07-21 23:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0003_especie_raca_especie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='sobre_nome',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(default=33357573877, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve conter exatamente 11 números.', regex='^\\d{11}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
