# Generated by Django 5.2.4 on 2025-07-23 14:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0005_animal_delete_cachorro'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='data_criacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.especie'),
        ),
    ]
