# Generated by Django 5.2.4 on 2025-07-24 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0007_funcionario_produtoservico_veterinario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='veterinario',
            name='cpf',
            field=models.CharField(default=0, max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='O CPF deve conter exatamente 11 números.', regex='^\\d{11}$')]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='especie',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='raca',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
