# Generated by Django 5.2.4 on 2025-07-30 00:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0009_cadastro_produto_venda_itemvenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produtoservico',
            name='tipo',
            field=models.CharField(choices=[('produto', 'Produto'), ('servico', 'Serviço'), ('vacina', 'Vacina')], max_length=10),
        ),
        migrations.CreateModel(
            name='AtendimentoClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('anamnese', models.TextField()),
                ('sintomas', models.TextField(blank=True, null=True)),
                ('diagnostico', models.TextField()),
                ('tratamento', models.TextField(blank=True, null=True)),
                ('exames_solicitados', models.TextField(blank=True, null=True)),
                ('orientacoes_ao_tutor', models.TextField(blank=True, null=True)),
                ('retorno_recomendado', models.BooleanField(default=False)),
                ('data_retorno', models.DateField(blank=True, null=True)),
                ('venda_gerada', models.BooleanField(default=False)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('agendamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.agendamento')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.animal')),
                ('veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.veterinario')),
            ],
        ),
        migrations.CreateModel(
            name='VacinaAplicada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_aplicacao', models.DateTimeField(default=django.utils.timezone.now)),
                ('dosagem', models.CharField(blank=True, max_length=50, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacinas_aplicadas', to='clinica.animal')),
                ('atendimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.atendimentoclinico')),
                ('vacina', models.ForeignKey(limit_choices_to={'tipo': 'vacina'}, on_delete=django.db.models.deletion.PROTECT, to='clinica.produtoservico')),
                ('veterinario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinica.veterinario')),
            ],
        ),
    ]
