# Generated by Django 5.2.4 on 2025-07-25 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempedido',
            old_name='preco_promocional',
            new_name='desconto',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='variacao',
        ),
        migrations.RemoveField(
            model_name='itempedido',
            name='variacao_id',
        ),
    ]
