# Generated by Django 5.2.4 on 2025-07-25 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinica', '0008_veterinario_cpf_alter_especie_nome_alter_raca_nome'),
        ('pedido', '0002_rename_preco_promocional_itempedido_desconto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itempedido',
            name='produto_id',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='usuario',
        ),
        migrations.AddField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clinica.cliente'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default='2025-07-25 00:00:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedido.pedido'),
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinica.produtoservico'),
        ),
    ]
